import { AfterContentInit, AfterViewInit, ElementRef, OnInit } from "@angular/core";
import { DatatablesTemplateDirective } from "../datatables-template/datatables-template.directive";
export declare class DatatablesPortletComponent implements OnInit, AfterViewInit, AfterContentInit {
    private elementRef;
    private toolsPanelElementRef?;
    private actionsPanelElementRef?;
    private filterPanelElementRef?;
    private datatablesComponent?;
    private templates;
    actionsTemplate: DatatablesTemplateDirective;
    filtersTemplate: DatatablesTemplateDirective;
    toolsTemplate: DatatablesTemplateDirective;
    captionTemplate: DatatablesTemplateDirective;
    caption?: string;
    description?: string;
    iconClass?: string;
    filterClass?: string;
    filterTitle?: string;
    filterIconClass?: string;
    fullscreenClass?: string;
    fullscreenTitle?: string;
    fullscreenIconClass?: string;
    showFullscreenIconClass?: string;
    hideFullscreenIconClass?: string;
    constructor(elementRef: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngAfterContentInit(): void;
    readonly filtersData: Object;
    filters(): Object;
    resetFilters(): void;
    filtersPanel(): ElementRef;
    toggleFilter: Function;
    private initTools();
    private initActions();
    private initFilterTool($toolPanel);
    private initFullscreenTool($toolPanel);
    private initActionsToolbar($actionsPanel);
    private findTemplateFor(templateName);
    private serializeToJSON(form);
}
